server:
  port: 8080
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        watch:
          enabled: true
        watch-delay: 1000

      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: efc7c90ff3c01911e1f8
            client-secret: b9dc1544c00186ad1bc57c53fa52f5409060bce4
            redirect-uri: http://localhost:8080/login/oauth2/code/github
  config:
    import:
      - optional:nacos:application-@profiles.active@.yml
security:
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzcDcTGeplWKCLWSbjeTcLtai72OtwMNr+9e4d4hlhYyGEc29ul26mTi7Hm0gyOI4hB4e299PPhAvFWO/EE//hHwyf3E1YBpFOGV/iVUI044I217iASok4XEHj9+DdxF3eYmVLCSk88WH4W/8PDG6y3zoPp0XEQy1yCqwfks2KTRTwbcKEJGthBgybxkXJC7/4XWA0K0aMbfDVHGbLPi21xobeKRdPXRNqAane15612gjJc/Q4m3nGLvBd/V1KnzEw/DH2qa2S+8LpCGdMLG7UOatIr0L9jg3SpWKUA96W2Ycjg1O61KiEtm3wT0t+CvSRzFou0O1cfMlHX1fHbdG9QIDAQAB
  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDNwNxMZ6mVYoItZJuN5Nwu1qLvY63Aw2v717h3iGWFjIYRzb26XbqZOLsebSDI4jiEHh7b308+EC8VY78QT/+EfDJ/cTVgGkU4ZX+JVQjTjgjbXuIBKiThcQeP34N3EXd5iZUsJKTzxYfhb/w8MbrLfOg+nRcRDLXIKrB+SzYpNFPBtwoQka2EGDJvGRckLv/hdYDQrRoxt8NUcZss+LbXGht4pF09dE2oBqd7XnrXaCMlz9DibecYu8F39XUqfMTD8MfaprZL7wukIZ0wsbtQ5q0ivQv2ODdKlYpQD3pbZhyODU7rUqIS2bfBPS34K9JHMWi7Q7Vx8yUdfV8dt0b1AgMBAAECggEABGoEz+bRbpEEdfDYnXyxdJfKOxSKX75RjL+eB4J3mxverHcbgOoN3MeozAhPUb/4smzrAJCT5KL4P586NCFjO/ZmJvHI0Vz+6yzSRaH7ZH6BliM8+gVrcSK5pM6IxX8sbwESoDXRDCHKvn1mjewLM95kJSO9oPIC3F5+FteKO+wHnBzxwx1J8aVRWsjwMvJV7IlvSB3DWulbvhb7VjIyJ8udPX5dTLiGfiOK9ZYloxuVIDm5Ehwb2ILCfavrGOjfUnwtQrpCgFy+B5SIfHqAtvNMG91BJRjJJaolFqjVTvp6HNPHvH84pD8q4r4mSRsNSw81XA23CUQ3HwKe2JNcqQKBgQDax5JtA9kw3sl41MiYSYgMMW7sU6Kd7dMbWfau4F/Gw8yCCMQh7hPKjcXCr60E45skqXjIII3NQnR6nAMF7XkpCv2A8edzuUHf7/WdEGoWw7MfQikhikEhys20ey52N1xjDBobKW5hsxz0d0CLmXCzLQhL3PshZlUg8qiHsr2urwKBgQDwwfZjgLG9S375rNU7gbOJ7JeL1Jybdab+v1r7YRM6un3X3qaNDApZ1Q7OAzUPwsg3sVoTWSYGycl2HuBzdRlqUIeIqAPcfyZczknZV3N89VjeggOG8Z9HTmJ2pBi8zQtYxPlKSNF46iaGfd9QkjJ9wwla6KX3pQ/tAKL6heJtmwKBgQC6rBSNPf5gy4deuThbcEpMFRXPQeF8HYPGT7HDLyGpqEFkJnSreseaSfOWlWzswgQLeSrcn6I+pFhckaemtCRwV7dMAZv6SvUhTU7l8C6FNAAvSLVtr9i5K6DvQTe4mK4UuSvBR02uwTSQhvwk4QyfZWoxyODic71pOoOAHYvpcwKBgAodC72YTV8XSckxMm/ifelAUAlmsAFzysUOwsKmjEk+RkUILFTmeZTWd12+Er+Lvh9gytjfONK2LUlR+LnA5IVrxpW+AROFH9ZsL/v6SXapU8ddDMrhYYB8UXSMZiGgN2bON26ganQ62c1ygiv/SDGyPLVd6oLhoy6ghTgi4aUbAoGAaRTzAiZcxoITrzmhxGh33cO5UYagExR8jv+mgSmRLvN3+eGlAHAJ7gysW1Ik4Wj8PW8lKM7XNDHTn3FMgBd4OXtEnJsE6UqfMRXGQhzt3i5VIHVpmcDuvO8p9rb2NZeCFCnb2G89ljqGdekuJpkiH34dHVsxUWd+PAHWW2GOSFk=

swagger:
  oauth2:
    authorization-url: http://127.0.0.1:${server.port}/oauth2/authorize?scope=message.read
    token-url: http://127.0.0.1:${server.port}/oauth2/token
    redirect-url: http://127.0.0.1:${server.port}/webjars/oauth/oauth2.html
    scopes:
      openid: openid
  info:
    description: OAuth2 认证服务
    title: OAuth2 认证服务
    version: @knife4j-openapi3.version@
    terms-of-service: https://www.vipicu.com

springdoc:
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
  group-configs:
    # fixme 必须为default 详情：https://gitee.com/xiaoym/knife4j/issues/I7RAP7
    - group: default
      paths-to-match: /**
  cache:
    disabled: true
