server:
  port: 8080
spring:
  application:
    name: oauth-authorization-server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://nas.r:2345/oauth
    password: postgres_password
    username: postgres
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:nas.r}:${NACOS_PORT:8848}
        watch:
          enabled: true
        watch-delay: 1000
        namespace: f9ae50e3-892b-47e8-9775-73bda8c3fd0b
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: f9ae50e3-892b-47e8-9775-73bda8c3fd0b
  config:
    import:
      - optional:nacos:application-dev.yml
# 日志
logging:
  config: classpath:log4j2-delayed.xml
  level:
    com.vipicu: debug
