server:
  port: 9999
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        watch:
          enabled: true
        watch-delay: 1000
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}

    gateway:
      routes:
        - id: spring-cloud-oauth-authorization
          uri: lb://spring-cloud-oauth-authorization
          predicates:
            - Path=/auth/**
        - id: spring-cloud-service-resource01
          uri: lb://spring-cloud-service-resource01
          predicates:
            - Path=/res01/**
        - id: spring-cloud-service-resource02
          uri: lb://spring-cloud-service-resource02
          predicates:
            - Path=/res02/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  config:
    import:
      - optional:nacos:application-@profiles.active@.yml

knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      version: openapi3
      enabled: true
      excluded-services:
        - @artifactId@
#        - ${spring.cloud.gateway.routes[0].id}
      service-config:
        spring-cloud-service-resource01:
          group-name: 资源服务01
        spring-cloud-service-resource02:
          group-name: 资源服务02
    tags-sorter: order
    operations-sorter: order
