server:
  port: 9999
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        watch:
          enabled: true
        watch-delay: 1000
        namespace: f9ae50e3-892b-47e8-9775-73bda8c3fd0b
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: f9ae50e3-892b-47e8-9775-73bda8c3fd0b

    gateway:
      routes:
        - id: resource
          uri: lb://resource
          predicates:
            - Path=/res/**
      discovery:
        locator:
          enabled: true


  config:
    import:
      - optional:nacos:application-dev.yml

