spring:
  application:
    name: @artifactId@
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://nas.r:2345/oauth
#    password: postgres_password
#    username: postgres
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        watch:
          enabled: true
        watch-delay: 1000
        
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        
  config:
    import:
      - optional:nacos:application-@profiles.active@.yml
server:
  port: 8081

