spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        watch:
          enabled: true
        watch-delay: 1000

      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}

  config:
    import:
      - optional:nacos:application-@profiles.active@.yml
server:
  port: 8081
security:
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzcDcTGeplWKCLWSbjeTcLtai72OtwMNr+9e4d4hlhYyGEc29ul26mTi7Hm0gyOI4hB4e299PPhAvFWO/EE//hHwyf3E1YBpFOGV/iVUI044I217iASok4XEHj9+DdxF3eYmVLCSk88WH4W/8PDG6y3zoPp0XEQy1yCqwfks2KTRTwbcKEJGthBgybxkXJC7/4XWA0K0aMbfDVHGbLPi21xobeKRdPXRNqAane15612gjJc/Q4m3nGLvBd/V1KnzEw/DH2qa2S+8LpCGdMLG7UOatIr0L9jg3SpWKUA96W2Ycjg1O61KiEtm3wT0t+CvSRzFou0O1cfMlHX1fHbdG9QIDAQAB

swagger:
  oauth2:
    authorization-url: http://127.0.0.1:8080/oauth2/authorize?scope=message.read
    token-url: http://127.0.0.1:8080/oauth2/token
    redirect-url: http://127.0.0.1:${server.port}/webjars/oauth/oauth2.html
    scopes:
      openid: openid
  info:
    description: OAuth2 资源服务例子
    title: OAuth2 资源服务
    version: @knife4j-openapi3.version@
    terms-of-service: https://www.vipicu.com

springdoc:
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
  group-configs:
    # fixme 必须为default 详情：https://gitee.com/xiaoym/knife4j/issues/I7RAP7
    - group: default
      paths-to-match: /**
  cache:
    disabled: true

# 日志
logging:
  level:
    com.vipicu: debug
